case "${ACTION}" in
post)
	case "${ARCH}" in
		x86_64*)
			# Regenerate initramfs.
			echo "Regenerating initramfs, please wait..."
			dracut -f -q --regenerate-all
			;;
		*)
			echo "Nvidia has dropped support for 32-bit kernels.\n"
			echo "Please consider installing the nvidia390 package as an alternative.\n"
			echo "This package is now only useful if you're using a x86_64 kernel.\n"
			;;
	esac
	;;
esac
